<!-- eslint-disable @stylistic/max-len -->
<script setup lang="ts">
const faqs = [
  {
    question: 'What is Whirlombre?',
    answer: 'Whirlombre is a super-minimal library & tool designed to generate smooth shades. It\'s a lightweight tool meant to simplify and enhance the shading process in various design projects.'
  },
  {
    question: 'How do I integrate Whirlombre into my project?',
    answer: 'Integrating Whirlombre is straightforward. Simply follow the installation guide provided in our documentation, and you\'ll be up and running in no time. Given its minimal nature, it\'s designed to fit effortlessly into any project.'
  },
  {
    question: 'Does Whirlombre impact my project\'s performance?',
    answer: 'No, Whirlombre is crafted with performance in mind. Its lightweight structure ensures that there\'s no significant impact on your project\'s load time or responsiveness.'
  },
  {
    question: 'Is Whirlombre suitable for both web and mobile projects?',
    answer: 'Absolutely! Whirlombre\'s versatility makes it apt for both web and mobile design applications. It seamlessly adjusts to various platforms, ensuring consistent shading results.'
  },
  {
    question: 'Can I customize the shades generated by Whirlombre?',
    answer: 'Yes, Whirlombre offers customizable options, allowing you to tweak the generated shades to fit your specific design needs. Our comprehensive documentation provides guidance on all available customization features.'
  },
  {
    question: 'Is there a community or forum for Whirlombre users?',
    answer: 'Being open source, Whirlombre has a growing community of contributors and users. You can join the community forum or our GitHub repository for discussions, troubleshooting, or sharing your creations and experiences.'
  }
]
</script>

<template>
  <BaseContainer class="mb-12">
    <div class="mx-auto max-w-4xl">
      <MotionContainer type="fade-in">
        <h2 class="mb-16 text-center text-3xl leading-10 tracking-tight font-headline text-surface-900">
          Frequently asked questions
        </h2>
      </MotionContainer>

      <dl class="mt-10 space-y-px">
        <MotionContainer
          v-for="{ answer, question } in faqs"
          :key="question"
          type="fade-in">
          <BaseAccordion class="rounded-wl-small bg-surface-50 transition-colors hover:bg-surface-100">
            <template #header="{ isExpanded }">
              <span class="text-base font-semibold leading-7">{{ question }}</span>
              <span class="ml-6 h-7 flex items-center">
                <BaseIcon
                  class="shrink-0"
                  :icon="isExpanded ? 'expand_less' : 'expand_more'"
                  :size="24" />
              </span>
            </template>
            <template #content>
              <p class="mx-3 mb-3 text-base leading-7 text-surface-600">
                {{ answer }}
              </p>
            </template>
          </BaseAccordion>
        </MotionContainer>
      </dl>
    </div>
  </BaseContainer>
</template>
