<script setup lang="ts">
const faqs = [
    {
        question: 'What is Whirlombre?',
        answer: "Whirlombre is a super-minimal library designed to generate smooth shades. It's a lightweight tool meant to simplify and enhance the shading process in various design projects."
    },
    {
        question: 'How do I integrate Whirlombre into my project?',
        answer: "Integrating Whirlombre is straightforward. Simply follow the installation guide provided in our documentation, and you'll be up and running in no time. Given its minimal nature, it's designed to fit effortlessly into any project."
    },
    {
        question: "Does Whirlombre impact my project's performance?",
        answer: "No, Whirlombre is crafted with performance in mind. Its lightweight structure ensures that there's no significant impact on your project's load time or responsiveness."
    },
    {
        question: 'Is Whirlombre suitable for both web and mobile projects?',
        answer: "Absolutely! Whirlombre's versatility makes it apt for both web and mobile design applications. It seamlessly adjusts to various platforms, ensuring consistent shading results."
    },
    {
        question: 'Can I customize the shades generated by Whirlombre?',
        answer: 'Yes, Whirlombre offers customizable options, allowing you to tweak the generated shades to fit your specific design needs. Our comprehensive documentation provides guidance on all available customization features.'
    },
    {
        question: 'Is there a community or forum for Whirlombre users?',
        answer: 'Being open source, Whirlombre has a growing community of contributors and users. You can join the community forum or our GitHub repository for discussions, troubleshooting, or sharing your creations and experiences.'
    }
]
</script>

<template>
    <div class="mx-auto max-w-7xl px-6 py-24 sm:py-32 lg:px-8 lg:py-36">
        <div class="mx-auto max-w-4xl">
            <AnimFadeIn>
                <h2 class="text-3xl text-center font-headline leading-10 tracking-tight text-surface-900 mt-6 mb-12">Frequently asked questions</h2>
            </AnimFadeIn>

            <dl class="mt-10 space-y-1">
                <AnimFadeIn
                    v-for="it in faqs"
                    :key="it.question">
                    <!-- <HeadlessDisclosure
                        as="div"
                        class="bg-surface-50 hover:bg-surface-100 rounded-sm"
                        v-slot="{ open }">
                        <dt>
                            <HeadlessDisclosureButton class="flex py-5 px-3 w-full items-start justify-between text-left text-surface-900">
                                <span class="text-base font-semibold leading-7">{{ it.question }}</span>
                                <span class="ml-6 flex h-7 items-center">
                                    <BaseIcon
                                        class="shrink-0"
                                        :icon="open ? 'navArrowUp' : 'navArrowDown'"
                                        :size="24" />
                                </span>
                            </HeadlessDisclosureButton>
                        </dt>
                        <HeadlessDisclosurePanel
                            as="dd"
                            class="pr-12 px-3 pb-3">
                            <p class="text-base leading-7 text-surface-600">{{ it.answer }}</p>
                        </HeadlessDisclosurePanel>
                    </HeadlessDisclosure> -->
                    <BaseAccordion :question="it.question" :answer="it.answer" />
                </AnimFadeIn>
            </dl>
        </div>
    </div>
</template>
