<!-- eslint-disable @stylistic/max-len -->
<script setup lang="ts">
const items = [
  {
    label: 'What is Whirlombre?',
    content: 'Whirlombre is a super-minimal library & tool designed to generate smooth shades. It\'s a lightweight tool meant to simplify and enhance the shading process in various design projects.'
  },
  {
    label: 'How do I integrate Whirlombre into my project?',
    content: 'Integrating Whirlombre is straightforward. Simply follow the installation guide provided in our documentation, and you\'ll be up and running in no time. Given its minimal nature, it\'s designed to fit effortlessly into any project.'
  },
  {
    label: 'Does Whirlombre impact my project\'s performance?',
    content: 'No, Whirlombre is crafted with performance in mind. Its lightweight structure ensures that there\'s no significant impact on your project\'s load time or responsiveness.'
  },
  {
    label: 'Is Whirlombre suitable for both web and mobile projects?',
    content: 'Absolutely! Whirlombre\'s versatility makes it apt for both web and mobile design applications. It seamlessly adjusts to various platforms, ensuring consistent shading results.'
  },
  {
    label: 'Can I customize the shades generated by Whirlombre?',
    content: 'Yes, Whirlombre offers customizable options, allowing you to tweak the generated shades to fit your specific design needs. Our comprehensive documentation provides guidance on all available customization features.'
  },
  {
    label: 'Is there a community or forum for Whirlombre users?',
    content: 'Being open source, Whirlombre has a growing community of contributors and users. You can join the community forum or our GitHub repository for discussions, troubleshooting, or sharing your creations and experiences.'
  }
]
</script>

<template>
  <UContainer class="pb-16">
    <div class="mx-auto max-w-4xl">
      <MotionContainer type="fade-in">
        <h2 class="mb-8 text-center font-headline text-3xl leading-10 tracking-tight text-gray-900 dark:text-gray-100">
          Frequently asked questions
        </h2>
      </MotionContainer>

      <MotionContainer type="fade-in">
        <UAccordion :items="items" :ui="{ wrapper: 'flex flex-col w-full' }">
          <template #default="{ item, open }">
            <UButton color="gray" variant="soft" class="mb-px py-4">
              <span class="truncate text-base">{{ item.label }}</span>

              <template #trailing>
                <UIcon
                  name="i-material-symbols-arrow-downward-alt"
                  class="ms-auto size-5 transition-transform duration-200"
                  :class="[open && 'rotate-180']" />
              </template>
            </UButton>
          </template>
        </UAccordion>
      </MotionContainer>
    </div>
  </UContainer>
</template>
